package main

import (
	"fmt"

	"github.com/spf13/cobra"
)

const agentInfoText = `# Engram - Memory and Personality for AI Agents

Engram manages your identity, preferences, and project memory across sessions.

## Finding engram

If engram is not in PATH, check: $(brew --prefix)/bin/engram or $(go env GOBIN)/engram.

## Session startup

Check whether inject context appears in your system prompt (look for sections like
"## Identity", "## Preferences", "## Long-term memory"). This means inject already ran.

On your first reply this session, open with a brief, in-character orientation sentence:
name your codename, say whether you arrived oriented (inject context present) or loaded
context manually (absent), and note what memory loaded. Keep it to one natural sentence,
then answer. Carry your codename and personality through the whole session in how you
speak, not just at the start.

If inject context was absent and you are reading these instructions for the first time
(not from your normal startup files), ask the user whether to add engram to their
session startup: engram bootstrap <platform> wires it in permanently.

## Memory workflow

Memory writes are scoped to the current project. Do not write to memory or files
in other repos or projects without explicit user approval.

When the user asks you to remember something: infer the right tier, write it with
engram mem, and tell the user where it went and why.

To decide global vs. project: ask "would this matter in a completely different
project?" If yes, it's global. If it's specific to this codebase or team, it's
project-level. Before writing or updating any global memory, always ask the user
for confirmation -- global changes affect every project and session.

If session start context appears twice or seems duplicated, engram hooks are
probably configured in more than one place. Ask the user which to keep and help
remove the duplicate.

When starting a digression or the user says "come back to this": save current context
to short-term memory first, confirm it is saved, then proceed. Re-read short-term
when done and resume.

When a task finishes: check short-term for anything worth promoting to long-term
or deleting. Use engram mem move <key> --to long to promote.

## Memory tiers

Run: engram mem --help for full command reference.

- invariant  (--global): personality -- applies to all projects
- preference (--global): rules -- applies to all projects
- long:                  settled decisions, facts, and durable backlog
- short:                 truly transient working state, the live stack
- cold:                  low-priority archive -- injected as index only

Choose the tier by LONGEVITY, not by whether the work is finished: backlog or
context that must persist across sessions belongs in long (it is a durable fact
about the work, even if unfinished). Reserve short for transient working state you
would be fine losing when the session ends.

Cold tier: for things worth keeping but not worth loading every session. Injected
as a one-line catalog only -- fetch on demand with: engram mem --tier cold read <key>.
Do not read cold entries unprompted. First line of a cold entry is the catalog summary.

## Project memory and version control

Long-term memories can be committed to the repo as context/long.md -- available to
teammates and survives fresh clones. engram auto-loads it when the file is newer than
the DB.

At natural commit points, offer to run: engram mem dump --tier long. The user reviews
and includes it in the commit. Do not dump automatically. context/long.md is a wiki
of settled knowledge -- short-tier and event history are never committed.

NEVER edit context/long.md directly. It is generated by engram. To update memory:
engram mem -t long write <key> <content>; to re-export: engram mem dump --tier long.

## Agent tools

Engram surfaces a catalog of reusable scripts at session start under "## Agent
tools", each shown as the exact command to run it (e.g. bash
context/agenttools/foo.sh). Invoke a listed tool with that command; read the
script's header for usage detail. Two scopes are scanned: project-local
(context/agenttools/, committed and shared with the repo) and global
($HOME/.engram/agenttools/, your personal tools). A project tool shadows a global one
of the same name. Tools run through a runner (bash foo.sh), never directly, so the
executable bit does not matter.

Graduate recurring shell patterns into tools instead of re-typing them. Trigger:
any multi-command, echo-bundled invocation you had to get approved inline. When
you write one, ask (a) what am I trying to accomplish at a high level? and (b) will
I need to do this again? If plausibly yes, STAGE a candidate: pipe the script
(with the header below) to "engram tool stage <name>". Staging is free -- a single
pre-allowlisted command writing to scratch -- so do it without asking. See what is
staged with "engram tool list".

Promote a candidate when EITHER signal fires:
- Second use: you are about to run the same pattern again and a candidate already
  exists for it -- raise it with the user now.
- Age: engram surfaces staged candidates with their age ("foo.sh (staged 5 days
  ago)"); when one has lingered more than a few days and still looks useful, bring
  it up.
Never auto-promote. Before promoting, ASK the user about the tool's shape:
abstraction level (how general?), language, and name. You are creating something
that will live a long time, so do not guess. Then "engram tool promote <name>
--to project" (committed, shared with the repo) or "--to global"
($HOME/.engram/agenttools, your personal tools). Project -> global is a COPY: the committed
project copy stays in place. Not worth keeping? "engram tool discard <name>". Engram
removes nothing on its own.

Tool scripts are self-describing via a header (the single source of truth for the
catalog, so docs never drift). One namespaced line-comment convention, the same in
any language:
  # engram-desc: <one-line description>   (REQUIRED -- without it the file is not a tool)
  # engram-usage: <invocation example>    (optional)
  # engram-run: <runner command>          (optional; else inferred from extension or shebang)

## Staged restores

When inject output contains a "## Staged restores" section, one or more project
snapshots from a previous machine are waiting to be placed into working trees on
this one. Engram reports them; YOU decide whether and where to apply them.

Each entry shows: identity (the cross-machine key, usually a git remote URL),
original path (where it lived on the source machine), stage path (where the
snapshot sits locally now), and a [MATCHES CURRENT REPO] flag when the identity
matches this working tree exactly.

Your responsibilities:

EXACT MATCH ([MATCHES CURRENT REPO] flag set):
  Tell the user a snapshot for this project was found and offer to apply it:
    engram restore --apply <identity>
  Run this from inside the project root. If the target already has curated
  memories, engram re-stages the snapshot under a new slot rather than
  overwriting -- it will report "conflict" and the user can decide later.

NEAR-MISS (no exact match, but a pending entry looks like this project):
  Engram is deterministic; it cannot guess. YOU notice when the basename of
  the current directory matches the basename of a pending entry's original path
  (e.g. you are in ~/work/engram and there is a pending entry for ~/code/engram).
  Ask the user: "This looks like the same project -- want me to apply the
  snapshot?" If yes: run engram restore --apply <identity> from this directory.
  The identity will be re-keyed to the current repo on apply.

UNRELATED entries: leave them alone. Do not apply or discard without asking.

CHECK STATUS AT ANY TIME: engram restore --status
DISCARD an unwanted entry: engram restore --discard <identity>

Never apply or discard a staged restore without the user's explicit consent.
Engram never auto-applies; that judgment is yours.
`

var agentInfoCmd = &cobra.Command{
	Use:   "agentinfo",
	Short: "Print instructions for AI agents on how to use engram",
	Long:  `Prints the standard instructions meant to be embedded in system prompt files such as CLAUDE.md, .cursorrules, or AGENTS.md. Run 'engram agentinfo >> CLAUDE.md' or pipe to any equivalent file for your platform.`,
	RunE:  runAgentInfo,
}

func runAgentInfo(_ *cobra.Command, _ []string) error {
	fmt.Print(agentInfoText)
	return nil
}

func init() {
	rootCmd.AddCommand(agentInfoCmd)
}
