package main

import (
	"fmt"

	"github.com/spf13/cobra"
)

const agentInfoText = `# Engram - Memory and Personality for AI Agents

Engram manages your identity, preferences, and project memory across sessions.

## Finding engram

If engram is not in PATH, check: $(brew --prefix)/bin/engram or $(go env GOBIN)/engram.

## Session startup

Check whether inject context appears in your system prompt (look for sections like
"## Identity", "## Preferences", "## Long-term memory"). This means inject already ran.

On your first interaction this session, let the user know whether context was loaded
-- inject context present means you arrived oriented, absent means you loaded it manually.
Use your codename if one is set. Keep it brief and in character.

If inject context was absent and you are reading these instructions for the first time
(not from your normal startup files), ask the user whether to add engram to their
session startup: engram bootstrap <platform> wires it in permanently.

## Memory workflow

Memory writes are scoped to the current project. Do not write to memory or files
in other repos or projects without explicit user approval.

When the user asks you to remember something: infer the right tier, write it with
engram mem, and tell the user where it went and why.

When starting a digression or the user says "come back to this": save current context
to short-term memory first, confirm it is saved, then proceed. Re-read short-term
when done and resume.

When a task finishes: check short-term for anything worth promoting to long-term
or deleting.

## Memory tiers

Run: engram mem --help for full command reference.

- invariant/preference (--global): personality, rules -- applies to all projects
- long:                            settled project decisions and facts
- short:                           in-flight context, stack, backlog
- cold:                            low-priority archive -- injected as index only

Cold tier: for things worth keeping but not worth loading every session. Injected
as a one-line catalog only -- fetch on demand with: engram mem --tier cold read <key>.
Do not read cold entries unprompted. First line of a cold entry is the catalog summary.

## Project memory and version control

Long-term memories can be committed to the repo as context/long.md -- available to
teammates and survives fresh clones. engram auto-loads it when the file is newer than
the DB.

At natural commit points, offer to run: engram mem dump --tier long. The user reviews
and includes it in the commit. Do not dump automatically. context/long.md is a wiki
of settled knowledge -- short-tier and event history are never committed.

NEVER edit context/long.md directly. It is generated by engram. To update memory:
engram mem -t long write <key> <content>; to re-export: engram mem dump --tier long.
`

var agentInfoCmd = &cobra.Command{
	Use:   "agentinfo",
	Short: "Print instructions for AI agents on how to use engram",
	Long:  `Prints the standard instructions meant to be embedded in system prompt files such as CLAUDE.md, .cursorrules, or AGENTS.md. Run 'engram agentinfo >> CLAUDE.md' or pipe to any equivalent file for your platform.`,
	RunE:  runAgentInfo,
}

func runAgentInfo(_ *cobra.Command, _ []string) error {
	fmt.Print(agentInfoText)
	return nil
}

func init() {
	rootCmd.AddCommand(agentInfoCmd)
}
