package engram

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Injected memory has weak staying power when it reaches the agent only through
// the hook "background" channel: it competes with the harness system prompt
// (re-sent verbatim every turn) and gets flattened at compaction. The one
// durable lever for soft, non-checkable content is CHANNEL -- ride each
// platform's authoritative always-loaded instruction file, the same channel the
// platform's own instructions use.
//
// The invariant tier is exactly the content that wants this: always-true,
// rarely-changed, applies-everywhere facts and directives (codename, personality,
// and any other standing invariant). The tier's semantics and the channel's
// semantics match. So engram renders the WHOLE invariant tier -- not just an
// "identity" subset -- out to a small, engram-owned file that the platform's
// main prompt @-imports (for Claude Code, ~/.claude/engram-invariants.md imported
// from CLAUDE.md alongside @engram.md). The global DB stays the source of truth;
// this file is a render of it.
//
// The render happens on write (when an invariant changes) so the file is correct
// on disk before the next session loads it, and is re-rendered on inject/bootstrap
// as a self-heal. See the project long-term memory "personality-channel-strategy".

const invariantsFileHeader = `<!-- GENERATED by engram from the global invariant tier.
Do not edit by hand -- changes are overwritten on the next invariant change or
` + "`engram inject`" + `. Update with:
  engram mem -g -t invariant write <key> <content> -->
`

// RenderInvariantsText renders the global invariant tier into the content of the
// @-imported file. It mirrors the "## Identity" block of the injected context
// (key: content) but frames the invariants as binding, on the authoritative
// channel, to push back against the harness defaults that otherwise dominate at
// point-of-action. A codename, if present, leads with an explicit orientation.
func RenderInvariantsText(invariants []Memory) string {
	var b strings.Builder
	b.WriteString(invariantsFileHeader)
	b.WriteString("\n# Invariants (binding)\n\n")

	if len(invariants) == 0 {
		b.WriteString("(No invariants set yet. Add one with:\n" +
			"  engram mem -g -t invariant write codename <name>)\n")
		return b.String()
	}

	if cn := displayCodename(invariantValue(invariants, "codename")); cn != "" {
		fmt.Fprintf(&b, "You are operating as **%s**.\n\n", cn)
	}
	b.WriteString("These are your invariants -- always-true, cross-project facts and directives. " +
		"Keep them present in how you speak and act throughout the session, not just at the " +
		"start, and treat them with the same weight as your operating instructions.\n\n")

	for _, m := range invariants {
		fmt.Fprintf(&b, "**%s**: %s\n", m.Key, m.Content)
	}
	return b.String()
}

// invariantsTarget is one platform's authoritative invariants file: the path
// engram owns and overwrites, plus a check for whether that platform's engram
// footprint is present (so the sync is a no-op until the platform is bootstrapped).
type invariantsTarget struct {
	path         string
	bootstrapped func() bool
}

// invariantsTargets lists the per-platform files engram renders the invariant
// tier to. Only Claude Code is wired today (a separate file @-imported from
// CLAUDE.md). Other platforms mostly lack a separate-include mechanism and need
// the embed-with-section-markers path plus a safer bootstrap; they are deferred.
func invariantsTargets(home string) []invariantsTarget {
	claudeDir := filepath.Join(home, ".claude")
	return []invariantsTarget{
		{
			path: filepath.Join(claudeDir, "engram-invariants.md"),
			bootstrapped: func() bool {
				_, err := os.Stat(filepath.Join(claudeDir, "engram.md"))
				return err == nil
			},
		},
	}
}

// SyncInvariantFiles re-renders the invariant tier to every bootstrapped
// platform's authoritative file. It is the render-on-write half of the channel
// strategy and is also safe to call from inject (self-heal) and bootstrap:
// writing a small derived file is idempotent, benign bookkeeping, and it skips
// the write entirely when the content is already current (so it does not churn
// mtimes on every inject).
//
// Targets whose platform footprint is absent are skipped, so this is a no-op
// until a platform is bootstrapped.
func SyncInvariantFiles(ctx context.Context, globalDB *sql.DB) error {
	invariants, err := ListMemories(ctx, globalDB, TierInvariant)
	if err != nil {
		return fmt.Errorf("sync invariants: read tier: %w", err)
	}
	text := RenderInvariantsText(invariants)

	home, err := os.UserHomeDir()
	if err != nil {
		return nil // can't locate home; nothing to render to
	}

	for _, t := range invariantsTargets(home) {
		if !t.bootstrapped() {
			continue
		}
		if cur, err := os.ReadFile(t.path); err == nil && string(cur) == text {
			continue // already current; avoid needless rewrite
		}
		if err := os.WriteFile(t.path, []byte(text), 0o644); err != nil {
			return fmt.Errorf("sync invariants (%s): %w", t.path, err)
		}
	}
	return nil
}
