package engram

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRenderInvariantsText(t *testing.T) {
	t.Run("with codename and another invariant", func(t *testing.T) {
		text := RenderInvariantsText([]Memory{
			{Tier: TierInvariant, Key: "codename", Content: "Cadence."},
			{Tier: TierInvariant, Key: "levity-default", Content: "React out loud to ugly code."},
		})
		for _, want := range []string{
			"GENERATED by engram",           // do-not-edit header
			"# Invariants (binding)",        // section
			"operating as **Cadence**",      // codename orientation
			"same weight as your operating", // authority framing
			"**codename**: Cadence.",        // rendered entry
			"**levity-default**: React out loud to ugly code.",
		} {
			if !strings.Contains(text, want) {
				t.Errorf("render missing %q\n--- got ---\n%s", want, text)
			}
		}
	})

	t.Run("empty renders a placeholder, not a bare header", func(t *testing.T) {
		text := RenderInvariantsText(nil)
		if !strings.Contains(text, "No invariants set yet") {
			t.Errorf("empty render missing placeholder:\n%s", text)
		}
		if strings.Contains(text, "operating as") {
			t.Error("empty render should not claim a codename")
		}
	})
}

func TestSyncInvariantFiles(t *testing.T) {
	ctx := context.Background()

	t.Run("writes the file when the platform is bootstrapped", func(t *testing.T) {
		home := t.TempDir()
		t.Setenv("HOME", home)

		gdb, err := OpenGlobalDB(ctx)
		if err != nil {
			t.Fatal(err)
		}
		defer gdb.Close()
		if err := WriteMemory(ctx, gdb, Memory{Tier: TierInvariant, Key: "codename", Content: "Cadence."}); err != nil {
			t.Fatal(err)
		}

		// Simulate a bootstrapped Claude Code install: engram.md present.
		claudeDir := filepath.Join(home, ".claude")
		if err := os.MkdirAll(claudeDir, 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(claudeDir, "engram.md"), []byte("instructions"), 0o644); err != nil {
			t.Fatal(err)
		}

		if err := SyncInvariantFiles(ctx, gdb); err != nil {
			t.Fatalf("SyncInvariantFiles: %v", err)
		}

		got, err := os.ReadFile(filepath.Join(claudeDir, "engram-invariants.md"))
		if err != nil {
			t.Fatalf("invariants file not written: %v", err)
		}
		if !strings.Contains(string(got), "operating as **Cadence**") {
			t.Errorf("rendered file missing codename:\n%s", got)
		}
	})

	t.Run("no-op when the platform is not bootstrapped", func(t *testing.T) {
		home := t.TempDir()
		t.Setenv("HOME", home)

		gdb, err := OpenGlobalDB(ctx)
		if err != nil {
			t.Fatal(err)
		}
		defer gdb.Close()
		if err := WriteMemory(ctx, gdb, Memory{Tier: TierInvariant, Key: "codename", Content: "Cadence."}); err != nil {
			t.Fatal(err)
		}

		// No ~/.claude/engram.md -> not bootstrapped for Claude Code.
		if err := SyncInvariantFiles(ctx, gdb); err != nil {
			t.Fatalf("SyncInvariantFiles: %v", err)
		}
		if _, err := os.Stat(filepath.Join(home, ".claude", "engram-invariants.md")); !os.IsNotExist(err) {
			t.Error("invariants file should not be written when platform is not bootstrapped")
		}
	})
}
