package engram

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRenderInvariantsText(t *testing.T) {
	t.Run("with codename and another invariant", func(t *testing.T) {
		text := RenderInvariantsText([]Memory{
			{Tier: TierInvariant, Key: "codename", Content: "Cadence."},
			{Tier: TierInvariant, Key: "levity-default", Content: "React out loud to ugly code."},
		})
		for _, want := range []string{
			"GENERATED by engram",
			"# Invariants (binding)",
			"operating as **Cadence**",
			"same weight as your operating",
			"**codename**: Cadence.",
			"**levity-default**: React out loud to ugly code.",
		} {
			if !strings.Contains(text, want) {
				t.Errorf("render missing %q\n--- got ---\n%s", want, text)
			}
		}
	})

	t.Run("empty renders a placeholder, not a bare header", func(t *testing.T) {
		text := RenderInvariantsText(nil)
		if !strings.Contains(text, "No invariants set yet") {
			t.Errorf("empty render missing placeholder:\n%s", text)
		}
	})
}

func TestRenderPreferencesText(t *testing.T) {
	text := RenderPreferencesText([]Memory{
		{Tier: TierPreference, Key: "concise", Content: "Default to concise answers."},
	})
	for _, want := range []string{
		"# Preferences (standing defaults)",
		"yield to an explicit in-the-moment", // P2 framing: overridable
		"- Default to concise answers.",
	} {
		if !strings.Contains(text, want) {
			t.Errorf("preferences render missing %q\n--- got ---\n%s", want, text)
		}
	}
	// Preferences must NOT carry the unconditional invariant framing.
	if strings.Contains(text, "same weight as your operating") {
		t.Error("preferences should not be framed as binding like invariants")
	}
}

func TestSyncStandingMemory(t *testing.T) {
	ctx := context.Background()

	t.Run("writes both tier files when bootstrapped", func(t *testing.T) {
		home := t.TempDir()
		t.Setenv("HOME", home)

		gdb, err := OpenGlobalDB(ctx)
		if err != nil {
			t.Fatal(err)
		}
		defer gdb.Close()
		if err := WriteMemory(ctx, gdb, Memory{Tier: TierInvariant, Key: "codename", Content: "Cadence."}); err != nil {
			t.Fatal(err)
		}
		if err := WriteMemory(ctx, gdb, Memory{Tier: TierPreference, Key: "concise", Content: "Default to concise answers."}); err != nil {
			t.Fatal(err)
		}

		// Simulate a bootstrapped Claude Code install.
		claudeDir := filepath.Join(home, ".claude")
		if err := os.MkdirAll(claudeDir, 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(claudeDir, "engram.md"), []byte("instructions"), 0o644); err != nil {
			t.Fatal(err)
		}

		if err := SyncStandingMemory(ctx, gdb); err != nil {
			t.Fatalf("SyncStandingMemory: %v", err)
		}

		inv, err := os.ReadFile(filepath.Join(claudeDir, "engram-invariants.md"))
		if err != nil {
			t.Fatalf("invariants file not written: %v", err)
		}
		if !strings.Contains(string(inv), "operating as **Cadence**") {
			t.Errorf("invariants file missing codename:\n%s", inv)
		}
		pref, err := os.ReadFile(filepath.Join(claudeDir, "engram-preferences.md"))
		if err != nil {
			t.Fatalf("preferences file not written: %v", err)
		}
		if !strings.Contains(string(pref), "Default to concise answers.") {
			t.Errorf("preferences file missing entry:\n%s", pref)
		}
	})

	t.Run("no-op when not bootstrapped", func(t *testing.T) {
		home := t.TempDir()
		t.Setenv("HOME", home)

		gdb, err := OpenGlobalDB(ctx)
		if err != nil {
			t.Fatal(err)
		}
		defer gdb.Close()
		if err := WriteMemory(ctx, gdb, Memory{Tier: TierInvariant, Key: "codename", Content: "Cadence."}); err != nil {
			t.Fatal(err)
		}

		if err := SyncStandingMemory(ctx, gdb); err != nil {
			t.Fatalf("SyncStandingMemory: %v", err)
		}
		for _, base := range StandingFileBases() {
			if _, err := os.Stat(filepath.Join(home, ".claude", base)); !os.IsNotExist(err) {
				t.Errorf("%s should not be written when not bootstrapped", base)
			}
		}
	})
}
