package engram

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Injected memory has weak staying power: it competes with the harness system
// prompt (re-sent verbatim every turn) and is flattened at compaction. The
// durable lever for soft, non-checkable content is CHANNEL -- ride each
// platform's authoritative always-loaded instruction file, the same channel the
// platform's own instructions use.
//
// Two global tiers ride that channel, at two rungs of the priority ladder (see
// the "priority-ladder" project memory):
//   - P1 invariants  -- unconditional identity; binding, persists through tasks.
//   - P2 preferences -- standing defaults; ride the channel for staying power but
//     yield to the user's in-the-moment instruction.
//
// P0 (config/hooks) is enforced structurally and lives outside memory; project
// tiers (long/short/cold) are cwd-tied and never go on the global channel. The
// global DB stays the source of truth; each tier is RENDERED to its own
// engram-owned file the platform's main prompt @-imports (Claude Code:
// ~/.claude/engram-invariants.md and engram-preferences.md, both imported from
// CLAUDE.md alongside @engram.md). Render happens on write (mem) plus bootstrap
// and restore -- never in inject, which stays read-only.

// standingFileHeader is the generated-do-not-edit banner for a rendered tier.
func standingFileHeader(tier Tier) string {
	return fmt.Sprintf(`<!-- GENERATED by engram from the global %s tier. Do not edit by hand --
changes are overwritten on the next `+"`engram mem`"+` %s change. Update with:
  engram mem -g -t %s write <key> <content> -->
`, tier, tier, tier)
}

// RenderInvariantsText renders the global invariant tier (P1): binding identity,
// framed with the same weight as operating instructions to push back against the
// harness defaults that otherwise dominate at point-of-action.
func RenderInvariantsText(invariants []Memory) string {
	return RenderLayeredInvariantsText(PrimaryMemories(invariants), nil, "")
}

func RenderLayeredInvariantsText(invariants, layer []Memory, agent string) string {
	var b strings.Builder
	b.WriteString(standingFileHeader(TierInvariant))
	b.WriteString("\n# Invariants (binding)\n\n")

	if len(invariants) == 0 && len(layer) == 0 {
		b.WriteString("(No invariants set yet. Add one with:\n" +
			"  engram mem -g -t invariant write codename <name>)\n")
		return b.String()
	}

	if cn := displayCodename(invariantValue(invariants, "codename")); cn != "" {
		fmt.Fprintf(&b, "You are operating as **%s**.\n\n", cn)
	}
	b.WriteString("These are your invariants -- always-true, cross-project facts and directives. " +
		"Keep them present in how you speak and act throughout the session, not just at the " +
		"start, and treat them with the same weight as your operating instructions.\n\n")

	for _, m := range invariants {
		fmt.Fprintf(&b, "**%s**: %s\n", m.Key, m.Content)
	}
	if agent != "" && len(layer) > 0 {
		fmt.Fprintf(&b, "\n## %s layer\n\n", agent)
		b.WriteString("Apply these agent-specific invariants on top of the primary invariants.\n\n")
		for _, m := range layer {
			fmt.Fprintf(&b, "**%s**: %s\n", m.Key, m.Content)
		}
	}
	return b.String()
}

// RenderPreferencesText renders the global preference tier (P2): standing
// defaults that ride the authoritative channel for staying power but yield to
// the user's current instruction -- one rung below invariants, deliberately not
// framed as unconditional. Rules that must never yield belong in config/hooks.
func RenderPreferencesText(prefs []Memory) string {
	return RenderLayeredPreferencesText(PrimaryMemories(prefs), nil, "")
}

func RenderLayeredPreferencesText(prefs, layer []Memory, agent string) string {
	var b strings.Builder
	b.WriteString(standingFileHeader(TierPreference))
	b.WriteString("\n# Preferences (standing defaults)\n\n")

	if len(prefs) == 0 && len(layer) == 0 {
		b.WriteString("(No preferences set yet. Add one with:\n" +
			"  engram mem -g -t preference write <key> <content>)\n")
		return b.String()
	}

	b.WriteString("These are standing defaults: apply them unless the user's current instruction " +
		"says otherwise. They outrank your built-in defaults but yield to an explicit in-the-moment " +
		"request -- one rung below your invariants. (A rule that must NEVER yield belongs in config " +
		"or a hook, not here.)\n\n")

	for _, m := range prefs {
		fmt.Fprintf(&b, "- %s\n", m.Content)
	}
	if agent != "" && len(layer) > 0 {
		fmt.Fprintf(&b, "\n## %s layer\n\n", agent)
		b.WriteString("Apply these agent-specific preferences on top of the primary preferences.\n\n")
		for _, m := range layer {
			fmt.Fprintf(&b, "- %s\n", m.Content)
		}
	}
	return b.String()
}

// standingRender binds a global tier to the file it renders to and the function
// that frames it. The set is the global standing memory that rides the
// authoritative channel, ordered by priority (invariants before preferences).
type standingRender struct {
	tier     Tier
	fileBase string
	render   func([]Memory, []Memory, string) string
}

var standingRenders = []standingRender{
	{tier: TierInvariant, fileBase: "engram-invariants.md", render: RenderLayeredInvariantsText},
	{tier: TierPreference, fileBase: "engram-preferences.md", render: RenderLayeredPreferencesText},
}

// StandingFileBases returns the base names of the per-platform files engram
// renders standing global memory to, in priority order, so bootstrap can
// @-import them and uninstall can remove them.
func StandingFileBases() []string {
	names := make([]string, len(standingRenders))
	for i, s := range standingRenders {
		names[i] = s.fileBase
	}
	return names
}

// standingTarget is one platform's directory for the rendered files, plus a
// check for whether that platform's engram footprint is present (so the sync is
// a no-op until the platform is bootstrapped).
type standingTarget struct {
	dir          string
	agent        string
	bootstrapped func() bool
}

// standingTargets lists the per-platform directories engram renders to. Only
// Claude Code is wired today (separate files @-imported from CLAUDE.md). Other
// platforms mostly lack a separate-include mechanism and need the embed-with-
// section-markers path plus a safer bootstrap; they are deferred.
func standingTargets(home string) []standingTarget {
	claudeDir := filepath.Join(home, ".claude")
	return []standingTarget{
		{
			dir:   claudeDir,
			agent: "claude",
			bootstrapped: func() bool {
				_, err := os.Stat(filepath.Join(claudeDir, "engram.md"))
				return err == nil
			},
		},
	}
}

// SyncStandingMemory re-renders every standing global tier (invariants,
// preferences) to each bootstrapped platform's authoritative files. It is the
// render-on-write half of the channel strategy and is also safe to call from
// bootstrap and restore: writing small derived files is idempotent, benign
// bookkeeping, and it skips a write when content is already current (so it does
// not churn mtimes). It must NOT be called from inject -- inject stays read-only,
// and a hook-time render cannot reach the current session anyway.
//
// Targets whose platform footprint is absent are skipped, so this is a no-op
// until a platform is bootstrapped.
func SyncStandingMemory(ctx context.Context, globalDB *sql.DB) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil // can't locate home; nothing to render to
	}

	for _, t := range standingTargets(home) {
		if !t.bootstrapped() {
			continue
		}
		for _, s := range standingRenders {
			mems, err := ListMemories(ctx, globalDB, s.tier)
			if err != nil {
				return fmt.Errorf("sync standing: read %s: %w", s.tier, err)
			}
			text := s.render(PrimaryMemories(mems), AgentLayerMemories(mems, t.agent), t.agent)
			path := filepath.Join(t.dir, s.fileBase)
			if cur, err := os.ReadFile(path); err == nil && string(cur) == text {
				continue // already current
			}
			if err := os.WriteFile(path, []byte(text), 0o644); err != nil {
				return fmt.Errorf("sync standing (%s): %w", path, err)
			}
		}
	}
	return nil
}
