package engram

import (
	"context"
	"strings"
	"testing"
)

func TestRenderInvariantsText(t *testing.T) {
	t.Run("with codename and another invariant", func(t *testing.T) {
		text := RenderInvariantsText([]Memory{
			{Tier: TierInvariant, Key: "codename", Content: "Cadence."},
			{Tier: TierInvariant, Key: "levity-default", Content: "React out loud to ugly code."},
		})
		for _, want := range []string{
			"GENERATED by engram",
			"# Invariants (binding)",
			"operating as **Cadence**",
			"same weight as your operating",
			"**codename**: Cadence.",
			"**levity-default**: React out loud to ugly code.",
		} {
			if !strings.Contains(text, want) {
				t.Errorf("render missing %q\n--- got ---\n%s", want, text)
			}
		}
	})

	t.Run("empty renders a placeholder, not a bare header", func(t *testing.T) {
		text := RenderInvariantsText(nil)
		if !strings.Contains(text, "No invariants set yet") {
			t.Errorf("empty render missing placeholder:\n%s", text)
		}
	})
}

func TestRenderPreferencesText(t *testing.T) {
	text := RenderPreferencesText([]Memory{
		{Tier: TierPreference, Key: "concise", Content: "Default to concise answers."},
	})
	for _, want := range []string{
		"# Preferences (standing defaults)",
		"yield to an explicit in-the-moment", // P2 framing: overridable
		"- Default to concise answers.",
	} {
		if !strings.Contains(text, want) {
			t.Errorf("preferences render missing %q\n--- got ---\n%s", want, text)
		}
	}
	// Preferences must NOT carry the unconditional invariant framing.
	if strings.Contains(text, "same weight as your operating") {
		t.Error("preferences should not be framed as binding like invariants")
	}
}

func TestSyncStandingMemory(t *testing.T) {
	ctx := context.Background()
	written, err := SyncStandingMemory(ctx, nil)
	if err != nil {
		t.Fatalf("SyncStandingMemory: %v", err)
	}
	if len(written) != 0 {
		t.Errorf("compatibility sync reported %d writes, want no-op", len(written))
	}
	want := []string{"engram-invariants.md", "engram-preferences.md"}
	for i, got := range StandingFileBases() {
		if got != want[i] {
			t.Errorf("StandingFileBases()[%d] = %q, want %q", i, got, want[i])
		}
	}
}
