package engram

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
)

// These renderers are retained for callers that explicitly want a markdown view
// of standing memory. Engram no longer installs or synchronizes their output:
// identity and preferences have one delivery path through session injection,
// while the durable init file contains only the policy kernel.

// standingFileHeader is the generated-do-not-edit banner for a rendered tier.
func standingFileHeader(tier Tier) string {
	return fmt.Sprintf(`<!-- GENERATED by engram from the global %s tier. Do not edit by hand --
changes are overwritten on the next `+"`engram mem`"+` %s change. Update with:
  engram mem -g -t %s write <key> <content> -->
`, tier, tier, tier)
}

// RenderInvariantsText renders the global invariant tier (P1): binding identity,
// framed with the same weight as operating instructions to push back against the
// harness defaults that otherwise dominate at point-of-action.
func RenderInvariantsText(invariants []Memory) string {
	return RenderLayeredInvariantsText(PrimaryMemories(invariants), nil, "")
}

func RenderLayeredInvariantsText(invariants, layer []Memory, agent string) string {
	var b strings.Builder
	b.WriteString(standingFileHeader(TierInvariant))
	b.WriteString("\n# Invariants (binding)\n\n")

	if len(invariants) == 0 && len(layer) == 0 {
		b.WriteString("(No invariants set yet. Add one with:\n" +
			"  engram mem -g -t invariant write codename <name>)\n")
		return b.String()
	}

	if cn := displayCodename(invariantValue(invariants, "codename")); cn != "" {
		fmt.Fprintf(&b, "You are operating as **%s**.\n\n", cn)
	}
	b.WriteString("These are your invariants -- always-true, cross-project facts and directives. " +
		"Keep them present in how you speak and act throughout the session, not just at the " +
		"start, and treat them with the same weight as your operating instructions.\n\n")

	for _, m := range invariants {
		fmt.Fprintf(&b, "**%s**: %s\n", m.Key, m.Content)
	}
	if agent != "" && len(layer) > 0 {
		fmt.Fprintf(&b, "\n## %s layer\n\n", agent)
		b.WriteString("Apply these agent-specific invariants on top of the primary invariants.\n\n")
		for _, m := range layer {
			fmt.Fprintf(&b, "**%s**: %s\n", m.Key, m.Content)
		}
	}
	return b.String()
}

// RenderPreferencesText renders the global preference tier (P2): standing
// defaults that yield to the user's current instruction and are deliberately not
// framed as unconditional. Rules that must never yield belong in config/hooks.
func RenderPreferencesText(prefs []Memory) string {
	return RenderLayeredPreferencesText(PrimaryMemories(prefs), nil, "")
}

func RenderLayeredPreferencesText(prefs, layer []Memory, agent string) string {
	var b strings.Builder
	b.WriteString(standingFileHeader(TierPreference))
	b.WriteString("\n# Preferences (standing defaults)\n\n")

	if len(prefs) == 0 && len(layer) == 0 {
		b.WriteString("(No preferences set yet. Add one with:\n" +
			"  engram mem -g -t preference write <key> <content>)\n")
		return b.String()
	}

	b.WriteString("These are standing defaults: apply them unless the user's current instruction " +
		"says otherwise. They outrank your built-in defaults but yield to an explicit in-the-moment " +
		"request -- one rung below your invariants. (A rule that must NEVER yield belongs in config " +
		"or a hook, not here.)\n\n")

	for _, m := range prefs {
		fmt.Fprintf(&b, "- %s\n", m.Content)
	}
	if agent != "" && len(layer) > 0 {
		fmt.Fprintf(&b, "\n## %s layer\n\n", agent)
		b.WriteString("Apply these agent-specific preferences on top of the primary preferences.\n\n")
		for _, m := range layer {
			fmt.Fprintf(&b, "- %s\n", m.Content)
		}
	}
	return b.String()
}

var legacyStandingFileBases = []string{"engram-invariants.md", "engram-preferences.md"}

// StandingFileBases returns the legacy generated filenames so bootstrap and
// uninstall can remove artifacts created by pre-kernel releases.
func StandingFileBases() []string {
	return append([]string(nil), legacyStandingFileBases...)
}

// SyncStandingMemory is retained as a compatibility no-op. Standing global
// memory is now injected at session boundaries rather than rendered into
// provider-specific files.
//
// Deprecated: no replacement is needed; callers should rely on inject.
func SyncStandingMemory(context.Context, *sql.DB) ([]string, error) {
	return nil, nil
}
